version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql-password
      MYSQL_DATABASE: rickstoredb
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  springboot-app:
    image: rick-sanchez-store
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rickstoredb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql-password
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
